services:
  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - nestjs-boilerplate-network

  mongo:
    image: mongo:8.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - boilerplate-mongo-db:/data/db
    ports:
      - ${DATABASE_PORT}:27017
    networks:
      - nestjs-boilerplate-network

  api:
    image: 5unof4beach/nestjs-boiler-plate:latest
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - nestjs-boilerplate-network

volumes:
  boilerplate-mongo-db:

networks:
  nestjs-boilerplate-network:
    driver: bridge

